### ISSUE TITLE
Transactions are still agregated

### ISSUE THREAD

**Issue by fones** [AfterShip/koa-newrelic#7]
Still see /* in NewRelic.

Problem is also mentioned in StackOverflow:
http://stackoverflow.com/questions/38886721/how-to-configure-newrelic-on-node-koa-app

**Comment by aobo-y** [comment]
hi @fones , could you at least share your router config 
see if it relates to the issue https://github.com/alexmingoia/koa-router/issues/246#issuecomment-244779462

currently it's a known issue if you have a such a wildcard route at end

Otherwise, you should have routes as following
<img width="345" alt="screen shot 2017-02-14 at 5 45 45 pm" src="https://cloud.githubusercontent.com/assets/5113450/22923683/6c144db0-f2dd-11e6-84bd-1acda798bf05.png">

**Comment by fones** [comment]
After fighting with it for a while, I have done it with NewRelic config file - rules.

Check https://docs.newrelic.com/docs/agents/nodejs-agent/supported-features/nodejs-agent-api#rules

If it known issue we can close.
